server:
  port: 8084
spring:
  application:
    name: mail-server
  mail:
    host: smtp.gmail.com
    username: hakandrmz18@gmail.com
    password: scmzhaxxdlnqtfvi
    port: '587'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB