server:
  port: 8084
spring:
  mail:
    host: smtp.gmail.com
    username: hakandrmz18@gmail.com
    password: sdibncfknejupmoo
    port: '587'
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    defaultModelsExpandDepth: '-1'
    doc-expansion: 'null'
  paths-to-exclude: /swagger-resources/**
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    mail: mail.queue
  routing-keys:
    internal-mail: internal.mail.routing-key
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true